name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: git status
        run: git status

      - name: install sharp module
        run: pnpm add sharp

      - name: fetch tags
        run: git fetch --tags

      - name: auto version 
        run: pnpm release


  release:
    needs: build
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: pull latest version
        run: git pull --no-rebase

      - name: check package.json
        run: cat package.json

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build the extension
        run: pnpm build:chrome 
        
      - name: Package the extension into a zip artifact
        run: pnpm package
      
      - name: build folder
        run: cd build

      - name: exame build 
        run: ls

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip
          verbose: true