name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18]
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: install sharp module
        run: pnpm add sharp

      - name: fetch tags
        run: git fetch --tags

      - name: auto version 
        run: pnpm release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


  release:
    needs: build
    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true
 
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.4.1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: install sharp module
        run: pnpm add sharp

      - name: git status
        run: git status

      - name: git diff
        run: git stash

      - name: pull latest version
        run: git pull --no-rebase

      - name: Build the extension
        run: pnpm build:chrome 
        
      - name: Inject css
        run: pnpm inject:css

      - name: Package the extension into a zip artifact
        run: pnpm package

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip