name: Release

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"
    steps:
      - uses: actions/checkout@v3
      - name: Cache pnpm modules
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: git status
        run: git status

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3.4.1
        with:
          node-version: 18.x
          cache-dependency-path: '**/pnpm-lock.yaml'

      - name: git status
        run: git status
        
      - name: install pnpm frozen lockfile
        run: pnpm i --frozen-lockfile

      - name: git status
        run: git status

      - name: install sharp module
        run: pnpm add sharp

      - name: fetch tags
        run: git fetch --tags

      - name: auto version 
        run: pnpm release

      - name: Prepare repository
        run: git fetch --unshallow --tags

      - name: Build the extension
        run: pnpm build:chrome 
        
      - name: Package the extension into a zip artifact
        run: pnpm package

      - name: Browser Platform Publish
        uses: PlasmoHQ/bpp@v3
        with:
          keys: ${{ secrets.SUBMIT_KEYS }}
          artifact: build/chrome-mv3-prod.zip